### ISSUE TITLE
Add LICENSE file.

### ISSUE THREAD

**Issue by afs** [dice-group/LSQ#36]
A top level LICENSE means github will pick it up.

**Comment by saleem-muhammad** [comment]
Sorry I did not get it. Can you please further explain ?

**Comment by afs** [comment]
Hi @saleem-muhammad 

(This is related to a conversation with @Aklakan and @LorenzBuehmann .)

The convention in open source is to put a file named `LICENSE` in the top level directory with the license in it. It helps people find the license.

And it becoming for tools as well. github scans repos, determines the license from a set it knows about, and adds the information to the "about" panel and also puts it in the repositories listing for the organisation.

See for example: https://github.com/AKSW/gson-utils/LICENSE (@Aklakan).

The other convention is `NOTICE`, which is for the required legal statements that downstream. The Apache License does not have such a requirement. Apache Software Foundation put the copyright statement in their NOTICE file.

e.g.
https://github.com/apache/commons-lang/blob/master/NOTICE.txt

Happy to help - but not PR in this case. The LICENSE ought to be added by an owner!

**Comment by Aklakan** [comment]
@afs Thanks for pointing out the missing license - Its now the usual Apache V2.
