### ISSUE TITLE
build unsuccessful

### ISSUE THREAD

**Issue by hashimkhanwazir** [dice-group/LSQ#37]
`[ERROR] Failed to execute goal on project lsq-vocab-jena: Could not resolve dependencies for project org.aksw.simba.lsq:lsq-vocab-jena:jar:2.0.0-SNAPSHOT: Could not find artifact org.apache.jena:jena-core:jar:4.5.0-SNAPSHOT in maven.aksw.snapshots (https://maven.aksw.org/archiva/repository/snapshots)` During build process this error is generated. Any hints to resolve the issue please ...

**Comment by Aklakan** [comment]
Sigh, apparently the apache snapshot repository removes old snapshots:
There is no more 4.5.0-SNAPSHOT listed at https://repository.apache.org/content/repositories/snapshots/org/apache/jena/jena-arq/

I need to make a proper stable release of the code base.

**Comment by Aklakan** [comment]
The project now has a recent maven central release #53 which should have a corresponding stable build on the master branch.
