### ISSUE TITLE
SPIN API not available during build

### ISSUE THREAD

**Issue by miguel76** [dice-group/LSQ#41]
During build I get the following error:
```log
[ERROR] Failed to execute goal on project lsq-model: Could not resolve dependencies for project org.aksw.simba.lsq:lsq-model:jar:2.0.0-SNAPSHOT: Could not find artifact org.topbraid:spin:jar:2.0.0 in com.topquadrant.internal (https://www.topquadrant.com/repository/spin)
```

Turns out SPIN API is not available anymore at https://www.topquadrant.com/repository/spin, so the pointers from the register in Maven central repository are broken.

**Comment by Aklakan** [comment]
Created a maven central release for spinrdf under org.aksw.thirdparty.org.spinrdf and merged the namespaces updates from the PR #42 .
