### ISSUE TITLE
Upload LSQ to maven repository

### ISSUE THREAD

**Issue by nck-mlcnv** [dice-group/LSQ#53]
Hi, we want to integrate the query analysis of LSQ into Iguana. Therefore we need LSQ as an dependecy for the project, which would be much easier, if LSQ was available in a public maven repository. Would it be possible for you to upload LSQ to the central repository?

**Comment by Aklakan** [comment]
I just fixed the maven central deployment and the artifacts should appear there soon (in version 2.0.0-RC4).

I will create an updated release once jena 5.2.0 is out. Currently the dependencies mix javax and jakarta servlets which may cause huge pains when trying to integrate the project into one that already comes with a jetty server.

Let me know if there are any more issues to fix.

**Comment by Aklakan** [comment]
First release is now public: https://central.sonatype.com/search?q=org.aksw.simba.lsq
